/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;

import org.example.packets.PacketReader;
import org.example.primitives.VarIntField;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String hostName = args.length == 0 ? "127.0.0.1" : args[0];
        int portNumber = args.length <= 1 ? 25565 : Integer.parseInt(args[1]);

        try {
            ServerSocket serverSocket = new ServerSocket(portNumber);

            while(true){
                Socket clientSocket = serverSocket.accept();

                InputStream is = clientSocket.getInputStream();

                PacketReader.readPacket(is);

                clientSocket.close();

            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println(new App().getGreeting());
    }
}
