/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import org.example.sessions.ClientConnection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        int portNumber = args.length <= 1 ? 25565 : Integer.parseInt(args[0]);

        ServerSocket serverSocket = null;

        try {
            serverSocket = new ServerSocket(portNumber);

            while(true){
                Socket clientSocket = serverSocket.accept();

                ClientConnection clientConnection = new ClientConnection(clientSocket);

                clientConnection.start();
            }

        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if(serverSocket != null && !serverSocket.isClosed())
                    serverSocket.close();
            } catch (IOException e) {e.printStackTrace();}
        }

    }
}
